### PR TITLE
Renamed discovery endpoints

### PR DESCRIPTION
**Pull request by clintonb**
"Discovery" is ambiguous to the point of being meaningless. "Catalog" is well-understood and better represents the purpose of the API/IDA

### CODE REVIEW

**Comment by clintonb** [comment]
FYI @efagin @srpearce @bderusha @peter-fogg 

This stemmed from a conversation with Docs Wednesday afternoon. We have 2-3 APIs all dealing with courses and some variation of the name "course catalog discovery API". We agreed to call the mobile API "mobile course discovery" and the API hosted at edx/course-discovery "Catalog API". Note that "catalog" here is the registrar definition (e.g. all courses offered by edX) not the grouping definition (e.g. some subset of the group of courses).

**Comment by efagin** [comment]
+💯

**Comment by srpearce** [comment]
Quick correction to the names above: The ECOM API will be "Course Catalog," and the mobile API will be "Courses".

**Comment by peter-fogg** [comment]
Does this mean we get to rename all the apps in http://github.com/edx/course-discovery/? 😝 

👍

**Comment by clintonb** [comment]
@peter-fogg eventually, yes.

**Comment by bderusha** [comment]
image

**Pull request merged**
